### ISSUE TITLE
Exit code feature sometime inaccurate

### ISSUE THREAD

**Issue by derekbekoe** [oakeyc/azure-cli-interactive-shell#45]
The exit code thing doesn't work all the time?

![screen shot 2017-03-17 at 6 24 48 pm](https://cloud.githubusercontent.com/assets/16448634/24182269/ea94edd2-0e7d-11e7-8670-132be23859c0.png)

Sometimes it says 'account set' returned exit code 2 when it should have succeeded all the time.

**Comment by oakeyc** [comment]
resolved in pull request #46
