### ISSUE TITLE
Autocompletion error in `az account set --subscription`

### ISSUE THREAD

**Issue by itowlson** [oakeyc/azure-cli-interactive-shell#53]
Steps to reproduce:

1. Type `az account set --subscription`
2. Hit space bar to trigger autocompletion

Behaviour:

The autocomplete list of subscriptions appears, but so does a message saying `__main__.py account set: error: argument --subscription: expected one argument`.  The cursor is pushed down to the next line and backspacing produces strange visual artefacts (the autocomplete list appears again slightly offset, with bits of the first one still visible, and the error message is also redisplayed).  (Screenshot attached.)

![az-shell-set-subscription](https://cloud.githubusercontent.com/assets/865538/24425557/24c3bb12-1461-11e7-9fbe-81107d2c3a44.PNG)

**Comment by itowlson** [comment]
Environment is Windows 10, Python 3.5.3, azure-cli 2.0.1.

**Comment by oakeyc** [comment]
Which version azure-cli-shell are you using?

**Comment by itowlson** [comment]
0.1.1a21 - this is what I got when I ran the `pip --user --upgrade` command a couple of hours ago.
