### ISSUE TITLE
`az account` does not display autocompletion lists on space

### ISSUE THREAD

**Issue by itowlson** [oakeyc/azure-cli-interactive-shell#56]
Steps to reproduce:

1. Type `az` (space).  Autocompletion list of commands appears (network, vm, keyvault, etc.)
2. Type or select `account` and hit space.

Expected behaviour: autocompletion list of account commands appears.

Actual behaviour: list of account commands does not appear until you hit the first letter of a command (e.g. `s` displays a list containing `set` and `show`, `l` displays a list containing `list` and `list-locations`).

Additionally, after typing or selecting `set` and hitting space, command options are not displayed until you type `-` (and even then the command-specific options such as `--subscription` are not displayed until you type `--`).

Environment: Windows 10, Python 3.5.3, azure-cli 2.0.1, shell 0.1.1a21.

**Comment by oakeyc** [comment]
The double dash('--') behavior is because there are single dash('-') parameters, and I thought it would be cleaner to distinguish between them. Do you think it beneficial generate both completions?

**Comment by itowlson** [comment]
That's my feeling.  I tried a couple of commands and the options that appeared on the first dash were '--output', '-o', '--verbose' and '--debug' -- but usually I am _much_ more interested in the command-specific parameters such as the subscription ID for `account set` or the job or pool ID for `batch job create` .  So it would be great to have these appear as early as possible.  But perhaps other commands surface their key parameters as single-dash options, in which case your strategy would be really nice in terms of minimizing noise in the common case!

**Comment by oakeyc** [comment]
I think you're right about pulling the global parameters out of the first dash completion, which is fixed in PR #59
